### ISSUE TITLE
Windows exception on changing gain

### ISSUE THREAD

**Issue by majodi** [Manawyrm/sdrsharp-plutosdr#20]
I get an exception when trying to change the gain. Looks like there's something wrong with the communication with the Pluto device.

I tested with iio_info and that seems to work (I get a list of attributes) also the iio oscilloscope is working.
libiio-Version: v0.17

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Unable to write channel attribute -95
   at iio.Channel.ChannelAttr.write(String str)
   at SDRSharp.PlutoSDR.IIOHelper.SetAttribute(Device phy, String Channel, String Attribute, String Value, Boolean direction)
   at SDRSharp.PlutoSDR.PlutoSDRDevice.set_ManualGain(Int32 value)
   at SDRSharp.PlutoSDR.PlutoSDRControllerDialog.rxVga1GainTrackBar_Scroll(Object sender, EventArgs e)
   at System.Windows.Forms.TrackBar.OnScroll(EventArgs e)
   at System.Windows.Forms.TrackBar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SDRSharp
    Assembly Version: 1.0.0.1700
    Win32 Version: 1.0.0.1700
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
SDRSharp.Radio
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.Radio.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SDRSharp.Common
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.Common.DLL
----------------------------------------
SDRSharp.PanView
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.PanView.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SDRSharp.CollapsiblePanel
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.CollapsiblePanel.DLL
----------------------------------------
SDRSharp.FrequencyEdit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.FrequencyEdit.DLL
----------------------------------------
SDRSharp.HackRF
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.HackRF.DLL
----------------------------------------
SDRSharp.RTLSDR
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.RTLSDR.DLL
----------------------------------------
SDRSharp.RTLTCP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.RTLTCP.DLL
----------------------------------------
SDRSharp.FUNcube
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.FUNcube.DLL
----------------------------------------
SDRSharp.FUNcubeProPlus
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.FUNcubeProPlus.DLL
----------------------------------------
SDRSharp.SoftRock
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.SoftRock.DLL
----------------------------------------
SDRSharp.SDRIQ
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.SDRIQ.DLL
----------------------------------------
SDRSharp.SDRIP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.SDRIP.DLL
----------------------------------------
SDRSharp.AfedriSDRNet
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.AfedriSDRNet.DLL
----------------------------------------
SDRSharp.PlutoSDR
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.PlutoSDR.DLL
----------------------------------------
libiio-sharp
    Assembly Version: 0.17.0.0
    Win32 Version: 0.17.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/libiio-sharp.DLL
----------------------------------------
SDRSharp.DNR
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.DNR.DLL
----------------------------------------
SDRSharp.NoiseBlanker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.NoiseBlanker.DLL
----------------------------------------
SDRSharp.WavRecorder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.WavRecorder.DLL
----------------------------------------
SDRSharp.ZoomFFT
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.ZoomFFT.DLL
----------------------------------------
SDRSharp.BandPlan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.BandPlan.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SDRSharp.FrequencyManager
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.FrequencyManager.DLL
----------------------------------------
SDRSharp.Diagnostics
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/majod/Downloads/sdrsharp-x86/SDRSharp.Diagnostics.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by majodi** [comment]
Sorry, today after a reboot the problem seems to be gone. I'll do further testing.
